import {
  HomeTrendUp,
  Setting2,
  Tag2,
  Coin1,
  Home2,
  Sun1,
  Moon,
  Edit2,
  Trash,
  ArrowLeft2,
  ArrowRight2,
  Calendar2,
  SearchNormal1,
  CloseCircle,
  Add,
  Minus,
  Refresh,
  ArrowUp2,
  ArrowDown2,
} from "iconsax-reactjs";
import { Close } from "./custom_icons";

export const IconType = {
  HOME: (props) => <Home2 {...props} />,
  DASHBOARD: (props) => <HomeTrendUp {...props} />,
  TRANSACTIONS: (props) => <Coin1 {...props} />,
  CATEGORIES: (props) => <Tag2 {...props} />,
  SETTINGS: (props) => <Setting2 {...props} />,
  LIGHTMODE: (props) => <Sun1 {...props} />,
  DARKMODE: (props) => <Moon {...props} />,
  EDIT: (props) => <Edit2 {...props} />,
  DELETE: (props) => <Trash {...props} />,
  CALENDAR: (props) => <Calendar2 {...props} />,
  LEFT: (props) => <ArrowLeft2 {...props} />,
  RIGHT: (props) => <ArrowRight2 {...props} />,
  UP: (props) => <ArrowUp2 {...props} />,
  DOWN: (props) => <ArrowDown2 {...props} />,
  SEARCH: (props) => <SearchNormal1 {...props} />,
  CLEAR: (props) => <CloseCircle {...props} />,
  CLOSE: (props) => <Close {...props} />,
  PLUS: (props) => <Add {...props} />,
  MINUS: (props) => <Minus {...props} />,
  SWAP: (props) => <Refresh {...props} />,
};
